# air.toml

# Entrypoint of your application.
# It is automatically set to "main.go" or "build:PATH".
# You only need to set it when your entrypoint is not "main.go" and "build:PATH" fails to detect.
# entrypoint = "build:cmd/web/main.go"

# Build commands before running.
# It will only build targets upon start.
# build = ["go build -v ./cmd/web"]

# Directories to watch. "." for the current directory. Files starting with "." are ignored. No need to set if you use default value.
# dirs = ["."]

# Exclude directories/files. Prefix with '^' to negate the pattern.
# exclude_dir = ["assets", "templates"]
# exclude_file = ["main.log", "^\\.gitignore"]

# Auto reload when config file changes.
# Config file must be a .toml, .yaml, .yml, .json or .xml file.
# reload = true

# Environment variables to set. Format: KEY=VALUE.
# These variables are only valid for Air and won't pollute your system.
# env = ["VERSION=v1.0.0", "OS=macOS"]

# Custom binary name. Default is "air".
# binary = "air"

# Quiet mode. Suppresses verbose build output.
# quiet = false

# Suppresses log messages output to terminal.
# log_output = true

# Disable logging.
# disable_log = false

# Choose to watch changes only in the current directory.
# When set to true, if any watched directory is a sub-directory of another watched directory, changes in the parent directory will not trigger a hot reload.
# root = false

# Delay for the reload event.
# delay = 1000 # in milliseconds

# Suppress nested errors with file and line context in error messages.
# suppress_nested_errors = false

# Modify fsnotify events. Default is `Op|Create|Write|Chmod`.
# fsnotify = "Op|Create|Write|Chmod"

# Gracefully wait for connections to return before shutting down.
# grace = "1s"

# Log level: DEBUG, INFO, WARN or ERROR.
# log_level = "INFO"

# Launch, build and/or start commands after run. Could specify multiple commands for each with "|" separator.
# post_build = "echo Post-build"
# post_start = "echo Post-start"
# post_launch = "echo Post-launch"

# Execute a command before exiting.
# pre_exit = "echo 'I'm leaving'"

# Add watchers or events. Format: [watcher:events]
# watchers = ["files:.go$"]
# watchers = ["restart:main.go"]

# Ignore case for watcher paths.
# case_sensitive = true

# Filter out non-source files.
# only = ["*.go", "*.tmpl"]

# Include dot files.
# dot_files = false

# Global configuration, applies to all commands.
# [global]
# env = ["APP_PORT=9000"]

# Specific configurations for 'build' command.
# [build]
# env = ["BUILD_TAGS=debug"]
