apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}
spec:
  selector:
    app: {{ .Values.service }}
  type: ClusterIP  # Set type to ClusterIP for internal access
  ports:
  - port: 80
    targetPort: 80

