apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}  # Optional label
        POD: {{ .Values.POD }}  # Optional label
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.servicePort }}
        env:
        - name: CONFIG_VALUE
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-configmap
              key: config_key
        - name: SECRET_VALUE
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-secret
              key: secret_key

