apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    cloner.io/enabled: "True"
  labels:
    app: {{ .Values.app }}  # Optional label
    POD: {{ .Values.POD }}  # Optional label
