apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: {{ .Values.servicePort }}

